### ISSUE TITLE
Local endpoint not being processed, yet it returns data

### ISSUE THREAD

**Issue by adavie1** [ratiw/vuetable-2#111]
Firstly, love the component! Very cool!

It works fine with your demo API endpoint, I've also connected it successfully to a remote endpoint on a project cloud server.

However, what's really, really weird is that when I try and access a local endpoint (localhost:8000/api/sites)- which works fine in the browser, nothing shows up.

I know for a fact that JSON data IS being returned.

I get no errors of any kind. I'm seriously stuck. Any help would be much appreciated.

**Comment by cristijora** [comment]
Use [vue-devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd). Inspect your components and see if any data is saved. You can also see the imported components like vue-table in this case together with all their data, props and computed properties. Here is a starting [fiddle](http://jsfiddle.net/z11fe07p/1202/).
Make sure you don't have issues like [CORS](http://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin).

**Comment by adavie1** [comment]
Hi @cristijora, thanks for your reply!
I did use vue-devtools. For the cases where it worked, the data could clearly be seen. in this case, inspecting the object, just confirmed that "yup, it's got the right url" but nothing beyond that.

Thanks for doing the `fiddle.`  I can put my endpoint test route up for sure. The rest of the vuetable-2 code, is exactly like the tutorial, except the endpoint url is different.

Wouldn't CORS apply if I was accessing a domain outside of localhost? It's an idea though. Also, I don't get any browser warnings, and I can see the url results if I just type it into a browser window.

Thanks again for replying. I'll put my code up soon.

**Comment by adavie1** [comment]
OK! I've made some (odd) progress. Using **vue-tools** I can see the data under the `vuetable->tablePagination` property, it shows an Array[7] in which all the right objects are there. Yet the `vuetable->data` property is null.

This is the table definition:
```
  <vuetable ref="vuetable"
      api-url="http://localhost:8000/api/sites"
      :fields="fields"
      :css="css"
      pagination-path=""
      :multi-sort="true"
      multi-sort-key="ctrl"
      :sort-order="sortOrder"
      detail-row-component="my-detail-row"
      :append-params="moreParams"
      @vuetable:cell-clicked="onCellClicked"
      @vuetable:pagination-data="onPaginationData"
    ></vuetable>
    <div class="level-left">
      <div class="level-item">
    <vuetable-pagination-info ref="paginationInfo"
      ></vuetable-pagination-info>
```
This is the field definition:

```
  data () {
    return {
      css: {
        tableClass: 'table is-striped',
        ascendingIcon: 'fa fa-chevron-up',
        descendingIcon: 'fa fa-chevron-down',
        sortHandleIcon: 'fa fa-bars'
      },
      fields: [
        {
          name: '__checkbox',
          title: '#',
          titleClass: 'has-text-centered',
          dataClass: 'has-text-centered'
        },
        {
          name: 'id',
          sortField: 'id',
          titleClass: 'has-text-centered',
          dataClass: 'has-text-right',
          callback: 'formatNumber'
        },
        {
          name: 'siteName',
          title: 'Site Name',
          sortField: 'siteName'
        },
        {
          name: '__component:custom-actions',
          title: 'Actions',
          titleClass: 'has-text-centered',
          dataClass: 'has-text-centered'
        }
```
And lastly the output of: http://localhost:8000/api/sites
`[{"id":1,"siteName":"Bukit Pasir"},{"id":2,"siteName":"Batu 23 lenga"},{"id":3,"siteName":"Desaru 2"},{"id":4,"siteName":"Hentian Penawar"},{"id":5,"siteName":"Hotel Selesa"},{"id":6,"siteName":"Kampung Maju Jaya"},{"id":7,"siteName":"Parit Madirono Replacement"}]`

Any pointers as to where I might be messing up, greatly appreciated.
Thanks in advance.

**Comment by ratiw** [comment]
@adavie1 What is the browser you're using? Are you using the code from `master` branch or `develop` branch? Which version of Vue that you're using?

**Comment by adavie1** [comment]
Hi @ratiw , I'm using Vue 2.2.6 - testing in Chrome on Linux (Ubuntu 16.04). I installed using `npm install vuetable-2` so whatever branch that pulls from.

**Comment by ratiw** [comment]
@adavie1 Can you please update the `package.json` to make it refer to the `develop` branch 
```json
  "vuetable-2": "git://github.com/ratiw/vuetable-2.git#develop",
```

Run `npm update` and try again.

It looks like someone has mentioned this problem and we've already fixed that. The fix might be in the `develop` branch. If not, we'll try to figure it out what was wrong.

**Comment by adavie1** [comment]
@ratiw - just did that- now I have vuetable-2@1.5.0 but the issue still persists.

**Comment by ratiw** [comment]
Is there any error dumping out in the browser's console?

**Comment by ratiw** [comment]
Just notice that your JSON doesn't contain data structure that Vuetable expected. Try adding `data-path=""` to vuetable.

**Comment by adavie1** [comment]
@ratiw  - there are no errors in the console.

**Comment by ratiw** [comment]
Try the `data-path` I mentioned above.

**Comment by ratiw** [comment]
https://github.com/ratiw/vue-table/wiki/Data-Format-(JSON)

**Comment by adavie1** [comment]
I added this:
```
    <vuetable ref="vuetable"
      api-url="http://localhost:8000/api/sites"
      data-path=""
      :fields="fields"
...
```
Thanks for the link, I'll check it out and amend the JSON.

**Comment by ratiw** [comment]
Try fixing the JSON structure, then let us know.

**Comment by adavie1** [comment]
@ratiw  - thanks, will do.

**Comment by adavie1** [comment]
Hi @ratiw , Thanks for your patience in my reply- was tied up on another project.

Yes, adding "data" to the JSON value fixes the issue:

`{"data":[{"id":1,"siteName":"Bukit Pasir"},{"id":2,"siteName":"Batu 23 lenga"},{"id":3,"siteName":"Desaru 2"},{"id":4,"siteName":"Hentian Penawar"},{"id":5,"siteName":"Hotel Selesa"},{"id":6,"siteName":"Kampung Maju Jaya"},{"id":7,"siteName":"Parit Madirono Replacement"}]}
`
Now correctly displays the data.
Thanks for your support.
